<center>&copy; | Ghassen <strong>MARRAKCHI</strong> - 2022</center>

<img src="../__src/Institut_Galilee.png" style="">
<hr>

<h1 style="text-align:center;color:#5a84ba"><center>Méthodes Matricielles pour le Data Mining</center></h1>
<h2><center><strong><font color='#3f4a4f'>Factorisation Matricielle Non-Négative pour
le Text Mining
</font></strong></center></h2>

<hr>
<h3><center><strong><font color='#3f4a4f'>II- Pré-traitemnt du dataset</font></strong></center></h3>
<hr>

<h4><strong><font color='#353b38'>Plan de Travail</font></strong></h4>

<ol style="list-style-type: upper-roman;">
    <li><a href="./I-Introduction.ipynb">Introduction</a></li>
    <li><strong>Pré-traitemnt du dataset</strong></li>
    <li><a href="./III-Clustering simple.ipynb">Clustering simple</a></li>
    <li><a href="./IV-NMF.ipynb">NMF</a></li>
    <li><a href="./V-Orthogonal NMF.ipynb">Orthogonal NMF</a></li>
    <li><a href="./VI-Symmetric NMF.ipynb">Symmetric NMF</a></li>
    <li><a href="./VII-Conclusion.ipynb">Conclusion</a></li>
</ol>

<hr>
<h4><strong><font color='#353b38'>Objectif</font></strong></h4>

- Comprendre le type des données traitées (Text).
- Explorer le dataset.
- transformer le texte pour les questions suivantes.

<h4><strong><font color='#353b38'>Configuration générale du notebook</font></strong></h4>

In [1]:
# Packages Importation
import os
import scipy.io
import pandas as pd

from numpy import *
from sklearn.feature_extraction.text import TfidfTransformer

In [2]:
# Files paths


## BRUTE
BRUT_MAT_FILE = os.path.join('..', 'dataset', 'brute', 'Reuters21578.mat')
BRUT_DOC_FILE = os.path.join('..', 'dataset', 'brute', 'documents.csv')
BRUT_TER_FILE = os.path.join('..', 'dataset', 'brute', 'terms.csv')
BRUT_TOP_FILE = os.path.join('..', 'dataset', 'brute', 'topics.csv')


## PRE-TRAITEMENT
PRE_TRAIT_MAT_FILE        = os.path.join('..', 'dataset', 'II-pre-traite', 'data.csv')
PRE_TRAIT_MAT_TF_IDF_FILE = os.path.join('..', 'dataset', 'II-pre-traite', 'data_tf-idf.csv')
PRE_TRAIT_MAT_SORTED_FILE = os.path.join('..', 'dataset', 'II-pre-traite', 'data_sorted.csv')

PRE_TRAIT_LAB_FILE        = os.path.join('..', 'dataset', 'II-pre-traite', 'label.csv')
PRE_TRAIT_LAB_SORTED_FILE = os.path.join('..', 'dataset', 'II-pre-traite', 'label_sorted.csv')

PRE_TRAIT_DOC_FILE        = os.path.join('..', 'dataset', 'II-pre-traite', 'docs.csv')
PRE_TRAIT_DOC_SORTED_FILE = os.path.join('..', 'dataset', 'II-pre-traite', 'docs_sorted.csv')

PRE_TRAIT_TER_FILE        = os.path.join('..', 'dataset', 'II-pre-traite', 'terms.csv')

PRE_TRAIT_TOP_FILE        = os.path.join('..', 'dataset', 'II-pre-traite', 'topics.csv')

<h4><strong><font color='#353b38'>Implémentation des fonctions</font></strong></h4>

<h5 id="print_numpy_array_infos">print_numpy_array_infos</h5>

In [3]:
def print_numpy_array_infos(array, name) :
    """ Prints numpy array informations.
    
    Parameters
    ----------
    array : numpy.ndarray
        The array to print its informations
    name : str
        The name to be used for a formatted printing
    """
    
    print("ARRAY : ", name)
    print("--- Type               : ", type(array))
    print("--- Dimensions         : ", array.shape)
    print("--- Nombre de lignes   : ", array.shape[0])
    print("--- Nombre de colonnes : ", array.shape[1])
    print("--- Nombre totale des données décrites dans le dataset : ", array.size)
    print("--- Type des données : ", array.dtype)

    print("\n")

    print("AFFICHAGE (partie) : \n", array[:5,:])

<h4><strong><font color='#353b38'>Description du dataset</font></strong></h4>

<ul>
    <li><strong> Nom : </strong> Ruters21578 </li>
    <li><strong> URL : </strong> <a href="http://www.cad.zju.edu.cn/home/dengcai/Data/TextData.html">liens</a></li>
    <li><strong> Déscription : </strong> contient des documents de <strong>Reuters</strong> apparus dans son fil de presse. Ils sont catégorisées et pré-traités en enlevant la ponctuation, les mots d'arret ...  </li>
</ul>

Le dataset dans sa forme brute est constitué de trois fichiers : <br>
<ul>
    <li><strong> Ruters21578.mat : </strong> Contient la matrice des termes des documents. Chaque cellule est une valeur tf. </li>
    <li><strong> documents.csv : </strong> Contient la liste des documents, leurs classes et leurs appartenance technique (test/train) </li>
    <li><strong> terms.csv : </strong> Contient l'ensemble des termes du dataset </li>
    <li><strong> topics.csv : </strong> Contient les classes (labels) du dataset</li>
</ul>

<h4><strong><font color='#353b38'>Découverte des fichiers</font></strong></h4>

Nous allons procéder à la découverte de chaque fichier indépendament.

<h5>Ruters21578.mat</h5>

In [4]:
# Load .mat file
mat_file = scipy.io.loadmat(BRUT_MAT_FILE)
mat_file

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Wed Jan 16 00:53:49 2008',
 '__version__': '1.0',
 '__globals__': [],
 'gnd': array([[ 1],
        [ 1],
        [ 1],
        ...,
        [63],
        [64],
        [65]], dtype=uint8),
 'trainIdx': array([[   1],
        [   2],
        [   3],
        ...,
        [8286],
        [8288],
        [8290]], dtype=uint16),
 'testIdx': array([[2674],
        [2675],
        [2676],
        ...,
        [8291],
        [8292],
        [8293]], dtype=uint16),
 'fea': <8293x18933 sparse matrix of type '<class 'numpy.float64'>'
 	with 389455 stored elements in Compressed Sparse Column format>}

In [5]:
# Returned Data Structure
type(mat_file)

dict

Le dictionnaire retourné contient plusieurs champs : <br>
<ul>
    <li><strong> __header__ : </strong> Un ensemble de méta-données à propos du dataset. </li>
    <li><strong> __version__ : </strong> La version du dataset.  </li>
    <li><strong> __globals__ : </strong></li>
    <li><strong> gnd : </strong> Le tableau de labels des documents. Utilisable essentiellement comme target pour l'entrainement d'un modèle machine learning. </li>
    <li><strong> fea : </strong> La matrice des termes des documents de l'ensemble du corpus. Les lignes étant les documents et les colonnes sont les termes. Chaque cellule mets en évidence la valeur de tf (Term Frequency) dans chaque document </li>
    <li><strong> trainIdx : </strong> tableau des indices à utiliser pour l'entrainnement. </li>
    <li><strong> testIdx : </strong> tableau des indices à utiliser pour le test. </li>
</ul>

Il faut rappeler que le choix des IDs d'entrainnement et de test dès le début n'a pour but que l'uniformaisation des résultats. Il s''agit d'une condition experimentale pour avoir les même résultats.

Nous allons nous intéresser à <strong>"fea"</strong> et <strong>"gnd"</strong> pour former un format de dataset plus simple à analyser.

<h6>"gnd"</h6>

In [6]:
# Informations des labels
reuters_labels = mat_file['gnd']
print_numpy_array_infos(reuters_labels, "reuters_labels")

ARRAY :  reuters_labels
--- Type               :  <class 'numpy.ndarray'>
--- Dimensions         :  (8293, 1)
--- Nombre de lignes   :  8293
--- Nombre de colonnes :  1
--- Nombre totale des données décrites dans le dataset :  8293
--- Type des données :  uint8


AFFICHAGE (partie) : 
 [[1]
 [1]
 [1]
 [1]
 [1]]


<strong>| Définition de la fonction <a href="#print_numpy_array_infos"> print_numpy_array_infos</a> |</strong>

Pour des raisons de visibilité, nous afficherons une partie du tableau sous pandas.DataFrame

In [7]:
# Pandas DataFrame
reuters_labels = pd.DataFrame(reuters_labels)
reuters_labels.head()

0
0  1
1  1
2  1
3  1
4  1

<h6>"fea"</h6>

Il faut le transformer en un tableau numpy

In [8]:
# Informations Matrice des termes de documents
reuters_data = mat_file['fea'].toarray()
print_numpy_array_infos(reuters_data, "reuters_data")

ARRAY :  reuters_data
--- Type               :  <class 'numpy.ndarray'>
--- Dimensions         :  (8293, 18933)
--- Nombre de lignes   :  8293
--- Nombre de colonnes :  18933
--- Nombre totale des données décrites dans le dataset :  157011369
--- Type des données :  float64


AFFICHAGE (partie) : 
 [[1. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 2. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]]


<strong>| Définition de la fonction <a href="#print_numpy_array_infos"> print_numpy_array_infos</a> |</strong>

On va utiliser la fonctions <strong>.toarray()</strong> car il s'agit d'une sparse matrix.

In [9]:
# Pandas DataFrame
reuters_data = pd.DataFrame(reuters_data)
reuters_data.head()

0      1      2      3      4      5      6      7      8      9      ...  \
0    1.0    1.0    1.0    3.0    8.0    3.0    0.0    2.0    0.0    0.0  ...   
1    1.0    0.0    0.0    2.0    1.0    0.0    0.0    0.0    0.0    0.0  ...   
2    1.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    1.0    0.0  ...   
3    1.0    2.0    1.0    1.0    2.0    1.0    0.0    1.0    0.0    0.0  ...   
4    1.0    0.0    1.0    3.0    8.0    2.0    0.0    2.0    0.0    0.0  ...   

   18923  18924  18925  18926  18927  18928  18929  18930  18931  18932  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 18933 columns]

On remarque que les lignes et les colonnes sont indexée par des nombres : Il faut faire correspondre les nombres avec les vrais termes. On trouvera cela dans les autres fichiers

<h5>documents.csv</h5>

In [10]:
reuters_docs = pd.read_csv(BRUT_DOC_FILE)

In [11]:
# Informations des documents
print_numpy_array_infos(reuters_docs.to_numpy(), "reuters_docs")

ARRAY :  reuters_docs
--- Type               :  <class 'numpy.ndarray'>
--- Dimensions         :  (8293, 4)
--- Nombre de lignes   :  8293
--- Nombre de colonnes :  4
--- Nombre totale des données décrites dans le dataset :  33172
--- Type des données :  object


AFFICHAGE (partie) : 
 [['6504.txt' 1 'earn' 'Train']
 ['4253.txt' 1 'earn' 'Train']
 ['11728.txt' 1 'earn' 'Train']
 ['9115.txt' 1 'earn' 'Train']
 ['3874.txt' 1 'earn' 'Train']]


<strong>| Définition de la fonction <a href="#print_numpy_array_infos"> print_numpy_array_infos</a> |</strong>

In [12]:
# Pandas DataFrame
reuters_docs.head()

doc_index  label topic_name  split
0   6504.txt      1       earn  Train
1   4253.txt      1       earn  Train
2  11728.txt      1       earn  Train
3   9115.txt      1       earn  Train
4   3874.txt      1       earn  Train

On remarque que les lignes représentent les documents.

Pour chaque document, on a le nom, l'indice sujet (topic), le nom du sujet et la partie à laquelle il appartient (entrainement ou test)

<h5>terms.csv</h5>

In [13]:
reuters_terms = pd.read_csv(BRUT_TER_FILE)

In [14]:
# Informations des documents
print_numpy_array_infos(reuters_terms.to_numpy(), "reuters_terms")

ARRAY :  reuters_terms
--- Type               :  <class 'numpy.ndarray'>
--- Dimensions         :  (18933, 2)
--- Nombre de lignes   :  18933
--- Nombre de colonnes :  2
--- Nombre totale des données décrites dans le dataset :  37866
--- Type des données :  object


AFFICHAGE (partie) : 
 [['reuter' 8228]
 ['mln' 4090]
 ['dlrs' 3515]
 ['cts' 2928]
 ['vs' 2826]]


<strong>| Définition de la fonction <a href="#print_numpy_array_infos"> print_numpy_array_infos</a> |</strong>

In [15]:
# Pandas DataFrame
reuters_terms.head()

term  count
0  reuter   8228
1     mln   4090
2    dlrs   3515
3     cts   2928
4      vs   2826

On remarque que les lignes représentent les termes.

Pour chaque document, on a le terme et l'occurence totale dans tout les documents du dataset (Document Frequency)

<h5>topics.csv</h5>

In [16]:
reuters_topics = pd.read_csv(BRUT_TOP_FILE)

In [17]:
# Informations des documents
print_numpy_array_infos(reuters_topics.to_numpy(), "reuters_topics")

ARRAY :  reuters_topics
--- Type               :  <class 'numpy.ndarray'>
--- Dimensions         :  (65, 2)
--- Nombre de lignes   :  65
--- Nombre de colonnes :  2
--- Nombre totale des données décrites dans le dataset :  130
--- Type des données :  object


AFFICHAGE (partie) : 
 [[1 'earn']
 [2 'acq']
 [3 'crude']
 [4 'trade']
 [5 'money-fx']]


<strong>| Définition de la fonction <a href="#print_numpy_array_infos"> print_numpy_array_infos</a> |</strong>

In [18]:
# Pandas DataFrame
reuters_topics.head()

id      name
0   1      earn
1   2       acq
2   3     crude
3   4     trade
4   5  money-fx

On remarque que les lignes représentent les sujets (topics).

Pour chaque document, on a l'indice sujet (topic) et le nom du sujet.

<h4><strong><font color='#353b38'>Pré-traitement des fichiers</font></strong></h4>

Nous allons procéder à l'enregistrement des csv qui ne nécessite pas de pré-traitement.

In [19]:
# Enregistrement topic.csv
reuters_topics.to_csv(PRE_TRAIT_TOP_FILE, index=False)

<h5>Pré-traitement "terms.csv"</h5>

Nous allons ajouter les indices dans le tableau

In [20]:
reuters_terms.insert(0, "index", list(reuters_terms.index.values))
reuters_terms.head()

index    term  count
0      0  reuter   8228
1      1     mln   4090
2      2    dlrs   3515
3      3     cts   2928
4      4      vs   2826

In [21]:
# Enregistrement terms.csv
reuters_terms.to_csv(PRE_TRAIT_TER_FILE, index=False)

<h5>Pré-traitement "documents.csv"</h5>

Nous allons transformer la colonne des indices en des entiers.

In [22]:
# Transformation en un tableau numpy
reuters_docs_numpy = reuters_docs.to_numpy()
reuters_docs_index = reuters_docs_numpy[:, 0]
reuters_docs_index

array(['6504.txt', '4253.txt', '11728.txt', ..., '15206.txt', '17823.txt',
       '17880.txt'], dtype=object)

Nous allons enlever la partie '.txt' pour faciliter la transformation en **int** dans les prochaines étapes

In [23]:
for i in range(len(reuters_docs_index)) :
    reuters_docs_index[i] = int(reuters_docs_index[i].replace('.txt', ''))

reuters_docs_index

array([6504, 4253, 11728, ..., 15206, 17823, 17880], dtype=object)

In [24]:
# Insertion de la colonne des indices
reuters_docs_numpy[:, 0] = reuters_docs_index

In [25]:
# Pandas DataFrame
reuters_docs = pd.DataFrame(reuters_docs_numpy, columns=reuters_docs.columns)
reuters_docs.head()

doc_index label topic_name  split
0      6504     1       earn  Train
1      4253     1       earn  Train
2     11728     1       earn  Train
3      9115     1       earn  Train
4      3874     1       earn  Train

<i>- Non-Ordonnées</i>

In [26]:
# Enregistrement doc.csv
reuters_docs.to_csv(PRE_TRAIT_DOC_FILE, index=False)

<i>- Ordonnées</i>

Nous allons maintenant ordonner le doc.csv suivant les indices.

In [27]:
reuters_docs = reuters_docs.sort_values(by=['doc_index'])
reuters_docs.head()

doc_index label topic_name  split
7511         1    14      cocoa  Train
1293         9     1       earn  Train
4313        10     2        acq  Train
916         11     1       earn  Train
572         13     1       earn  Train

In [28]:
# Enregistrement doc.csv (ordonné)
reuters_docs.to_csv(PRE_TRAIT_DOC_SORTED_FILE, index=False)

<h5>Pré-traitement des données</h5>

<i>- Non-Ordonnées</i>

Nous allons d'abord enregistrer une version non ordonnée.

In [29]:
# Enregistrement
reuters_data.to_csv(PRE_TRAIT_MAT_FILE, index=False)

<strong><font color='#5a84ba'>Question 1.b/</font></strong>

<i>- TF-IDF</i>

Rappelons d'abord la formule de <strong>TF-IDF</strong> :

$$ \textrm{TF-IDF} = (1 + \log (\textrm{tf})) \times \log (\frac{\textrm{N}}{\textrm{df}})$$

Il faut noter que le problème qui survient est un problème issu de la conversion CSV

<ul>
    <li><strong> tf : </strong> Fréquence d'un terme dans un document</li>
    <li><strong> df : </strong> Occurance d'un terme dans le document  </li>
    <li><strong> N : </strong> Nombre de documents total</li>
</ul>

In [30]:
# Importation des fichiers
reuters_data_pandas = reuters_data
reuters_data = reuters_data.to_numpy()
reuters_terms = reuters_terms.to_numpy()

1- tranformer les colonnes en des termes

In [31]:
# Vérification du nombre des termes
termes = reuters_terms[:,1]

print("Nombre de termes  =", termes.shape[0])
print("Confirmation de l'égalité entre nombre de termes : ", termes.shape[0] == reuters_data.shape[1])

Nombre de termes  = 18933
Confirmation de l'égalité entre nombre de termes :  True


In [32]:
termes_str = []
for i in range(termes.shape[0]) :
    termes_str.append(str(termes[i]))

print("Nombre de termes comptés : ", len(termes_str))

Nombre de termes comptés :  18933


Nous allons substituer les indices des colonnes par la liste générée

In [33]:
reuters_data_pandas.columns = termes_str
reuters_data_pandas.head()

reuter  mln  dlrs  cts   vs  net  pct  shr  company  1986  ...  surges  \
0     1.0  1.0   1.0  3.0  8.0  3.0  0.0  2.0      0.0   0.0  ...     0.0   
1     1.0  0.0   0.0  2.0  1.0  0.0  0.0  0.0      0.0   0.0  ...     0.0   
2     1.0  0.0   0.0  0.0  0.0  1.0  0.0  0.0      1.0   0.0  ...     0.0   
3     1.0  2.0   1.0  1.0  2.0  1.0  0.0  1.0      0.0   0.0  ...     0.0   
4     1.0  0.0   1.0  3.0  8.0  2.0  0.0  2.0      0.0   0.0  ...     0.0   

   substituting  388.1  siege  toits  montedision  petroli  5952000  scrapped  \
0           0.0    0.0    0.0    0.0          0.0      0.0      0.0       0.0   
1           0.0    0.0    0.0    0.0          0.0      0.0      0.0       0.0   
2           0.0    0.0    0.0    0.0          0.0      0.0      0.0       0.0   
3           0.0    0.0    0.0    0.0          0.0      0.0      0.0       0.0   
4           0.0    0.0    0.0    0.0          0.0      0.0      0.0       0.0   

   richer  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0  

[5 rows x 18933 columns]

Nous allons appliquer tfidf transformer de scikit-learn

In [34]:
transformer = TfidfTransformer()

In [35]:
tfidf_trans = transformer.fit_transform(reuters_data_pandas)
tfidf_trans

<8293x18933 sparse matrix of type '<class 'numpy.float64'>'
	with 389455 stored elements in Compressed Sparse Row format>

In [36]:
reuters_data_pandas = pd.DataFrame(tfidf_trans.toarray(), index = reuters_data_pandas.index, columns=reuters_data_pandas.columns)
reuters_data_pandas.head()

reuter       mln      dlrs       cts        vs       net  pct       shr  \
0  0.023775  0.040260  0.043833  0.144426  0.391826  0.149121  0.0  0.108330   
1  0.069224  0.000000  0.000000  0.280349  0.142609  0.000000  0.0  0.000000   
2  0.047774  0.000000  0.000000  0.000000  0.000000  0.099885  0.0  0.000000   
3  0.048581  0.164537  0.089570  0.098374  0.200166  0.101572  0.0  0.110681   
4  0.027998  0.000000  0.051620  0.170083  0.461433  0.117075  0.0  0.127574   

   company  1986  ...  surges  substituting  388.1  siege  toits  montedision  \
0  0.00000   0.0  ...     0.0           0.0    0.0    0.0    0.0          0.0   
1  0.00000   0.0  ...     0.0           0.0    0.0    0.0    0.0          0.0   
2  0.10992   0.0  ...     0.0           0.0    0.0    0.0    0.0          0.0   
3  0.00000   0.0  ...     0.0           0.0    0.0    0.0    0.0          0.0   
4  0.00000   0.0  ...     0.0           0.0    0.0    0.0    0.0          0.0   

   petroli  5952000  scrapped  richer  
0      0.0      0.0       0.0     0.0  
1      0.0      0.0       0.0     0.0  
2      0.0      0.0       0.0     0.0  
3      0.0      0.0       0.0     0.0  
4      0.0      0.0       0.0     0.0  

[5 rows x 18933 columns]

Nous allons retourner le tableau à la version initiale (avec une indexation entière)

In [37]:
reuters_data_pandas.columns = reuters_terms[:,0]
reuters_data_pandas.head()

0         1         2         3         4         5      6      \
0  0.023775  0.040260  0.043833  0.144426  0.391826  0.149121    0.0   
1  0.069224  0.000000  0.000000  0.280349  0.142609  0.000000    0.0   
2  0.047774  0.000000  0.000000  0.000000  0.000000  0.099885    0.0   
3  0.048581  0.164537  0.089570  0.098374  0.200166  0.101572    0.0   
4  0.027998  0.000000  0.051620  0.170083  0.461433  0.117075    0.0   

      7        8      9      ...  18923  18924  18925  18926  18927  18928  \
0  0.108330  0.00000    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   
1  0.000000  0.00000    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   
2  0.000000  0.10992    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   
3  0.110681  0.00000    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   
4  0.127574  0.00000    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   

   18929  18930  18931  18932  
0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0  

[5 rows x 18933 columns]

In [38]:
print_numpy_array_infos(reuters_data_pandas.to_numpy(), "reuters_data")

ARRAY :  reuters_data
--- Type               :  <class 'numpy.ndarray'>
--- Dimensions         :  (8293, 18933)
--- Nombre de lignes   :  8293
--- Nombre de colonnes :  18933
--- Nombre totale des données décrites dans le dataset :  157011369
--- Type des données :  float64


AFFICHAGE (partie) : 
 [[0.0237746  0.04026036 0.04383328 ... 0.         0.         0.        ]
 [0.06922406 0.         0.         ... 0.         0.         0.        ]
 [0.04777428 0.         0.         ... 0.         0.         0.        ]
 [0.04858139 0.16453732 0.08956962 ... 0.         0.         0.        ]
 [0.02799811 0.         0.05162019 ... 0.         0.         0.        ]]


<strong>| Définition de la fonction <a href="#print_numpy_array_infos"> print_numpy_array_infos</a> |</strong>

In [39]:
# Enregistrement data.csv (tf-idf)
reuters_data_pandas.to_csv(PRE_TRAIT_MAT_TF_IDF_FILE, index=False)

<i>- Ordonnées</i>

nous allons ordonner data suivant les documents

In [40]:
# Pandas DataFrame
reuters_data = pd.DataFrame(reuters_data)
reuters_data.head()

0      1      2      3      4      5      6      7      8      9      ...  \
0    1.0    1.0    1.0    3.0    8.0    3.0    0.0    2.0    0.0    0.0  ...   
1    1.0    0.0    0.0    2.0    1.0    0.0    0.0    0.0    0.0    0.0  ...   
2    1.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    1.0    0.0  ...   
3    1.0    2.0    1.0    1.0    2.0    1.0    0.0    1.0    0.0    0.0  ...   
4    1.0    0.0    1.0    3.0    8.0    2.0    0.0    2.0    0.0    0.0  ...   

   18923  18924  18925  18926  18927  18928  18929  18930  18931  18932  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 18933 columns]

In [41]:
reuters_data.insert(0, "index", list(reuters_docs_index))
reuters_data.head()

index    0    1    2    3    4    5    6    7    8  ...  18923  18924  \
0   6504  1.0  1.0  1.0  3.0  8.0  3.0  0.0  2.0  0.0  ...    0.0    0.0   
1   4253  1.0  0.0  0.0  2.0  1.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
2  11728  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  ...    0.0    0.0   
3   9115  1.0  2.0  1.0  1.0  2.0  1.0  0.0  1.0  0.0  ...    0.0    0.0   
4   3874  1.0  0.0  1.0  3.0  8.0  2.0  0.0  2.0  0.0  ...    0.0    0.0   

   18925  18926  18927  18928  18929  18930  18931  18932  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 18934 columns]

In [42]:
reuters_data = reuters_data.sort_values(by=['index'])
reuters_data.pop("index")
reuters_data.head()

0      1      2      3      4      5      6      7      8      9      \
7511    1.0    5.0   14.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
1293    1.0    2.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   
4313    1.0    1.0    4.0    0.0    0.0    0.0    2.0    0.0    4.0    0.0   
916     1.0    6.0    2.0    2.0    5.0    1.0    0.0    2.0    0.0    0.0   
572     1.0    8.0    0.0    7.0    9.0    1.0    0.0    4.0    0.0    1.0   

      ...  18923  18924  18925  18926  18927  18928  18929  18930  18931  \
7511  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1293  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4313  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
916   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
572   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      18932  
7511    0.0  
1293    0.0  
4313    0.0  
916     0.0  
572     0.0  

[5 rows x 18933 columns]

In [43]:
# Enregistrement data.csv (ordonné)
reuters_data.to_csv(PRE_TRAIT_MAT_SORTED_FILE, index=False)

<h5>Pré-traitement des labels</h5>

Nous allons d'abord changer le nom de la colonne pour plus de compréhension.

In [44]:
reuters_labels.columns = ["label"]
reuters_labels.head()

label
0      1
1      1
2      1
3      1
4      1

<i>- Non-Ordonnées</i>

Nous allons enregistrer une version non ordonnée

In [45]:
# Enregistrement
reuters_labels.to_csv(PRE_TRAIT_LAB_FILE, index=False)

<i>- Ordonnées</i>

Nous allons maintenant ordonner les données.

In [46]:
reuters_labels["label"] = reuters_docs['label'].to_list()
reuters_labels.head()

label
0     14
1      1
2      2
3      1
4      1

In [47]:
# Enregistrement labels.csv (ordonné)
reuters_labels.to_csv(PRE_TRAIT_LAB_SORTED_FILE, index=False)

<hr>
<div style="display: flex;">
    <div style="margin: 10px;"><strong><a href="./I-Introduction.ipynb">précédent</a></strong></div>
    <div style="margin: 10px;"><strong><a href="./III-Clustering simple.ipynb">suivant</a></strong></div>
</div>